blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/poli0981/randomizerMAC/blob/master/README.md
    about: Read the README before opening an issue
  - name: Code of Conduct
    url: https://github.com/poli0981/randomizerMAC/blob/master/CODE_OF_CONDUCT.md
    about: Please read our Code of Conduct
